# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/auth.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'protos/auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import field_mask_pb2 as google_dot_protobuf_dot_field__mask__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11protos/auth.proto\x12\x08\x61uthuser\x1a google/protobuf/field_mask.proto\"\x8c\x01\n\rSignupDetails\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x13\n\x0bphonenumber\x18\x02 \x01(\t\x12\x11\n\tuseremail\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\x12\x17\n\x0f\x63onfirmpassword\x18\x05 \x01(\t\x12\x16\n\x0eisProfessional\x18\x06 \x01(\x08\"n\n\x0eSignupResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x13\n\x0bphonenumber\x18\x03 \x01(\t\x12\x11\n\tuseremail\x18\x04 \x01(\t\x12\x16\n\x0eisProfessional\x18\x05 \x01(\x08\"3\n\x0cLoginDetails\x12\x11\n\tuseremail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\" \n\x0fValidateRequest\x12\r\n\x05token\x18\x01 \x01(\t\"g\n\x10ValidateResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x13\n\x0b\x61\x63\x63\x65ssToken\x18\x04 \x01(\t\x12\x14\n\x0crefreshToken\x18\x05 \x01(\t\":\n\rLoginResponse\x12\x13\n\x0b\x61\x63\x63\x65ssToken\x18\x01 \x01(\t\x12\x14\n\x0crefreshToken\x18\x02 \x01(\t\"$\n\x0cTokenRequest\x12\x14\n\x0crefreshtoken\x18\x01 \x01(\t\":\n\rTokenResponse\x12\x13\n\x0b\x61\x63\x63\x65sstoken\x18\x01 \x01(\t\x12\x14\n\x0crefreshtoken\x18\x02 \x01(\t\"&\n\x0cSignupUpdate\x12\x16\n\x0eisProfessional\x18\x01 \x01(\x08\"\x1f\n\rUpdateRequest\x12\x0e\n\x06userId\x18\x01 \x01(\x05\"8\n\x0eUpdateResponse\x12&\n\x04user\x18\x01 \x01(\x0b\x32\x18.authuser.SignupResponse2\xd6\x02\n\x0b\x43reateUsers\x12?\n\nUserSignup\x12\x17.authuser.SignupDetails\x1a\x18.authuser.SignupResponse\x12<\n\tUserLogin\x12\x16.authuser.LoginDetails\x1a\x17.authuser.LoginResponse\x12?\n\x0cRefreshToken\x12\x16.authuser.TokenRequest\x1a\x17.authuser.LoginResponse\x12\x46\n\rValidateToken\x12\x19.authuser.ValidateRequest\x1a\x1a.authuser.ValidateResponse\x12?\n\nUpdateUser\x12\x17.authuser.UpdateRequest\x1a\x18.authuser.UpdateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SIGNUPDETAILS']._serialized_start=66
  _globals['_SIGNUPDETAILS']._serialized_end=206
  _globals['_SIGNUPRESPONSE']._serialized_start=208
  _globals['_SIGNUPRESPONSE']._serialized_end=318
  _globals['_LOGINDETAILS']._serialized_start=320
  _globals['_LOGINDETAILS']._serialized_end=371
  _globals['_VALIDATEREQUEST']._serialized_start=373
  _globals['_VALIDATEREQUEST']._serialized_end=405
  _globals['_VALIDATERESPONSE']._serialized_start=407
  _globals['_VALIDATERESPONSE']._serialized_end=510
  _globals['_LOGINRESPONSE']._serialized_start=512
  _globals['_LOGINRESPONSE']._serialized_end=570
  _globals['_TOKENREQUEST']._serialized_start=572
  _globals['_TOKENREQUEST']._serialized_end=608
  _globals['_TOKENRESPONSE']._serialized_start=610
  _globals['_TOKENRESPONSE']._serialized_end=668
  _globals['_SIGNUPUPDATE']._serialized_start=670
  _globals['_SIGNUPUPDATE']._serialized_end=708
  _globals['_UPDATEREQUEST']._serialized_start=710
  _globals['_UPDATEREQUEST']._serialized_end=741
  _globals['_UPDATERESPONSE']._serialized_start=743
  _globals['_UPDATERESPONSE']._serialized_end=799
  _globals['_CREATEUSERS']._serialized_start=802
  _globals['_CREATEUSERS']._serialized_end=1144
# @@protoc_insertion_point(module_scope)
