# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import auth_pb2 as protos_dot_auth__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in protos/auth_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CreateUsersStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UserSignup = channel.unary_unary(
                '/authuser.CreateUsers/UserSignup',
                request_serializer=protos_dot_auth__pb2.SignupDetails.SerializeToString,
                response_deserializer=protos_dot_auth__pb2.SignupResponse.FromString,
                _registered_method=True)
        self.UserLogin = channel.unary_unary(
                '/authuser.CreateUsers/UserLogin',
                request_serializer=protos_dot_auth__pb2.LoginDetails.SerializeToString,
                response_deserializer=protos_dot_auth__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.RefreshToken = channel.unary_unary(
                '/authuser.CreateUsers/RefreshToken',
                request_serializer=protos_dot_auth__pb2.TokenRequest.SerializeToString,
                response_deserializer=protos_dot_auth__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.ValidateToken = channel.unary_unary(
                '/authuser.CreateUsers/ValidateToken',
                request_serializer=protos_dot_auth__pb2.ValidateRequest.SerializeToString,
                response_deserializer=protos_dot_auth__pb2.ValidateResponse.FromString,
                _registered_method=True)
        self.UpdateUser = channel.unary_unary(
                '/authuser.CreateUsers/UpdateUser',
                request_serializer=protos_dot_auth__pb2.UpdateRequest.SerializeToString,
                response_deserializer=protos_dot_auth__pb2.UpdateResponse.FromString,
                _registered_method=True)


class CreateUsersServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UserSignup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UserLogin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CreateUsersServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UserSignup': grpc.unary_unary_rpc_method_handler(
                    servicer.UserSignup,
                    request_deserializer=protos_dot_auth__pb2.SignupDetails.FromString,
                    response_serializer=protos_dot_auth__pb2.SignupResponse.SerializeToString,
            ),
            'UserLogin': grpc.unary_unary_rpc_method_handler(
                    servicer.UserLogin,
                    request_deserializer=protos_dot_auth__pb2.LoginDetails.FromString,
                    response_serializer=protos_dot_auth__pb2.LoginResponse.SerializeToString,
            ),
            'RefreshToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshToken,
                    request_deserializer=protos_dot_auth__pb2.TokenRequest.FromString,
                    response_serializer=protos_dot_auth__pb2.LoginResponse.SerializeToString,
            ),
            'ValidateToken': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateToken,
                    request_deserializer=protos_dot_auth__pb2.ValidateRequest.FromString,
                    response_serializer=protos_dot_auth__pb2.ValidateResponse.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=protos_dot_auth__pb2.UpdateRequest.FromString,
                    response_serializer=protos_dot_auth__pb2.UpdateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'authuser.CreateUsers', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('authuser.CreateUsers', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CreateUsers(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UserSignup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/authuser.CreateUsers/UserSignup',
            protos_dot_auth__pb2.SignupDetails.SerializeToString,
            protos_dot_auth__pb2.SignupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UserLogin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/authuser.CreateUsers/UserLogin',
            protos_dot_auth__pb2.LoginDetails.SerializeToString,
            protos_dot_auth__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/authuser.CreateUsers/RefreshToken',
            protos_dot_auth__pb2.TokenRequest.SerializeToString,
            protos_dot_auth__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/authuser.CreateUsers/ValidateToken',
            protos_dot_auth__pb2.ValidateRequest.SerializeToString,
            protos_dot_auth__pb2.ValidateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/authuser.CreateUsers/UpdateUser',
            protos_dot_auth__pb2.UpdateRequest.SerializeToString,
            protos_dot_auth__pb2.UpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
