# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/hire_notification.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'protos/hire_notification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eprotos/hire_notification.proto\x12\x04hire\"\xa4\x01\n\x0bHireRequest\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x11\n\tfrom_date\x18\x03 \x01(\t\x12\x0f\n\x07to_date\x18\x04 \x01(\t\x12\r\n\x05price\x18\x05 \x01(\x02\x12\x0f\n\x07message\x18\x06 \x01(\t\x12\x17\n\x0fprofessional_id\x18\x07 \x01(\x05\x12\x19\n\x11professional_user\x18\x08 \x01(\t\"0\n\x0cHireResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2G\n\x0bHireService\x12\x38\n\x0fSendHireRequest\x12\x11.hire.HireRequest\x1a\x12.hire.HireResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.hire_notification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HIREREQUEST']._serialized_start=41
  _globals['_HIREREQUEST']._serialized_end=205
  _globals['_HIRERESPONSE']._serialized_start=207
  _globals['_HIRERESPONSE']._serialized_end=255
  _globals['_HIRESERVICE']._serialized_start=257
  _globals['_HIRESERVICE']._serialized_end=328
# @@protoc_insertion_point(module_scope)
